workflows:
  ios-workflow:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # Критически важно: генерируем ios папку СНАЧАЛА
      - name: Generate iOS project
        script: |
          flutter create --platforms=ios . --overwrite
      
      - name: Install Flutter dependencies
        script: flutter pub get
      
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      
      # Флаг --no-codesign говорит Codemagic НЕ ПЫТАТЬСЯ подписывать приложение.
      # Это идеально для AltStore.
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
      
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      # Отключаем автоматическую отправку, так как это просто тест
      email:
        recipients:
          - temporary@example.com