name: Generate iOS Folder

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      
      - name: Generate iOS folder
        run: |
          flutter create --platforms=ios . --overwrite
          rm -rf ios/Pods ios/Podfile.lock
          
      - name: Upload iOS folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-folder
          path: ios/